server:
  port: 8002
spring:
  application:
    name: microservice-consumer-order
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/,http://localhost:8200/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: '*'
feign:
  circuitbreaker:
    enabled: true