eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/,http://localhost:8200/eureka/
---
spring:
  config:
    activate:
      on-profile: host1
server:
  port: 8100
---
spring:
  config:
    activate:
      on-profile: host2
server:
  port: 8200
