eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/,http://localhost:8200/eureka/
#清除com.nerflix的日志信息
#logging:
#  level:
#    com.netflix: error
---
spring:
  application:
    name: eureka1
  config:
    activate:
      on-profile: host1
server:
  port: 8100
---
spring:
  application:
    name: eureka2
  config:
    activate:
      on-profile: host2
server:
  port: 8200
