server:
  port: 8001
spring:
  application:
    name: microservice-provider-user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/,http://localhost:8200/eureka/
  instance:
    prefer-ip-address: true

